"""club logo color

Revision ID: 27354051c03c
Revises: aa23cb5f804a
Create Date: 2026-09-24 23:32:10.508392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27354051c03c'
down_revision = 'aa23cb5f804a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_color', sa.String(length=16), server_default='blue', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clubs', schema=None) as batch_op:
        batch_op.drop_column('logo_color')

    # ### end Alembic commands ###
