"""login failures

Revision ID: aa23cb5f804a
Revises: d3067427113a
Create Date: 2026-09-24 20:53:24.705018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa23cb5f804a'
down_revision = 'd3067427113a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_failures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_failures'))
    )
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.create_index('ix_login_failures_login_created_at', ['login', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_failures', schema=None) as batch_op:
        batch_op.drop_index('ix_login_failures_login_created_at')

    op.drop_table('login_failures')
    # ### end Alembic commands ###
