"""initial schema

Revision ID: d3067427113a
Revises: 
Create Date: 2026-09-24 14:56:26.577751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3067427113a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clubs'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_users_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('login', name=op.f('uq_users_login'))
    )
    op.create_table('club_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('vk', 'youtube', 'site', 'other', name='linktype', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_links_club_id_clubs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_club_links'))
    )
    with op.batch_alter_table('club_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_links_club_id'), ['club_id'], unique=False)

    op.create_table('club_members',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('member', 'organizer', name='clubrole', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('banned_by', sa.Integer(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by'], ['users.id'], name=op.f('fk_club_members_banned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_members_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_members_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('club_id', 'user_id', name=op.f('pk_club_members'))
    )
    with op.batch_alter_table('club_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_club_members_user_id'), ['user_id'], unique=False)

    op.create_table('meetups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('place', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('planned', 'live', 'finished', name='meetupstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('join_token', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_meetups_club_id_clubs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_meetups_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetups')),
    sa.UniqueConstraint('join_token', name=op.f('uq_meetups_join_token'))
    )
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.create_index('ix_meetups_club_id_date', ['club_id', 'date'], unique=False)

    op.create_table('disqualifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_disqualifications_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], name=op.f('fk_disqualifications_meetup_id_meetups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_disqualifications_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disqualifications')),
    sa.UniqueConstraint('meetup_id', 'user_id', name=op.f('uq_disqualifications_meetup_id_user_id'))
    )
    op.create_table('meetup_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=16), nullable=False),
    sa.Column('format', sa.Enum('ao5', 'mo3', 'bo3', 'bo5', 'bo1', name='format', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], name=op.f('fk_meetup_events_meetup_id_meetups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meetup_events')),
    sa.UniqueConstraint('meetup_id', 'event_id', name=op.f('uq_meetup_events_meetup_id_event_id'))
    )
    with op.batch_alter_table('meetup_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetup_events_event_id'), ['event_id'], unique=False)

    op.create_table('meetup_participants',
    sa.Column('meetup_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='participantstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_meetup_participants_decided_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], name=op.f('fk_meetup_participants_meetup_id_meetups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_meetup_participants_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('meetup_id', 'user_id', name=op.f('pk_meetup_participants'))
    )
    with op.batch_alter_table('meetup_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetup_participants_user_id'), ['user_id'], unique=False)

    op.create_table('scrambles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_event_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('scramble', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meetup_event_id'], ['meetup_events.id'], name=op.f('fk_scrambles_meetup_event_id_meetup_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scrambles')),
    sa.UniqueConstraint('meetup_event_id', 'attempt_number', name=op.f('uq_scrambles_meetup_event_id_attempt_number'))
    )
    op.create_table('series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('in_progress', 'completed', name='seriesstatus', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('best', sa.Integer(), nullable=True),
    sa.Column('average', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meetup_event_id'], ['meetup_events.id'], name=op.f('fk_series_meetup_event_id_meetup_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_series_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_series')),
    sa.UniqueConstraint('meetup_event_id', 'user_id', name=op.f('uq_series_meetup_event_id_user_id'))
    )
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_user_id'), ['user_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('penalty', sa.Enum('none', 'plus2', 'dnf', 'dns', name='penalty', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('entered_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("penalty IN ('dnf', 'dns') OR value IS NOT NULL", name=op.f('ck_attempts_value_required')),
    sa.CheckConstraint('attempt_number BETWEEN 1 AND 5', name=op.f('ck_attempts_attempt_number_range')),
    sa.CheckConstraint('value IS NULL OR value > 0', name=op.f('ck_attempts_value_positive')),
    sa.ForeignKeyConstraint(['entered_by'], ['users.id'], name=op.f('fk_attempts_entered_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_attempts_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts')),
    sa.UniqueConstraint('series_id', 'attempt_number', name=op.f('uq_attempts_series_id_attempt_number'))
    )
    op.create_table('club_records',
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=16), nullable=False),
    sa.Column('type', sa.Enum('single', 'average', name='recordtype', native_enum=False, create_constraint=True, length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('achieved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], name=op.f('fk_club_records_club_id_clubs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_club_records_series_id_series'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_club_records_user_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('club_id', 'event_id', 'type', name=op.f('pk_club_records'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_records')
    op.drop_table('attempts')
    with op.batch_alter_table('series', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_user_id'))

    op.drop_table('series')
    op.drop_table('scrambles')
    with op.batch_alter_table('meetup_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetup_participants_user_id'))

    op.drop_table('meetup_participants')
    with op.batch_alter_table('meetup_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetup_events_event_id'))

    op.drop_table('meetup_events')
    op.drop_table('disqualifications')
    with op.batch_alter_table('meetups', schema=None) as batch_op:
        batch_op.drop_index('ix_meetups_club_id_date')

    op.drop_table('meetups')
    with op.batch_alter_table('club_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_members_user_id'))

    op.drop_table('club_members')
    with op.batch_alter_table('club_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_club_links_club_id'))

    op.drop_table('club_links')
    op.drop_table('users')
    op.drop_table('clubs')
    # ### end Alembic commands ###
