"""fmc attempts

Revision ID: e8fb5dc472df
Revises: 27354051c03c
Create Date: 2026-09-25 03:40:59.686561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fb5dc472df'
down_revision = '27354051c03c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fmc_attempts',
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('draft', sa.Text(), nullable=False),
    sa.Column('draft_saved_at', sa.DateTime(), nullable=True),
    sa.Column('frozen_solution', sa.Text(), nullable=True),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('attempt_number BETWEEN 1 AND 5', name=op.f('ck_fmc_attempts_attempt_number_range')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('fk_fmc_attempts_series_id_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('series_id', 'attempt_number', name=op.f('pk_fmc_attempts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fmc_attempts')
    # ### end Alembic commands ###
